spring:
  r2dbc:
    url: r2dbc:mysql://remonair.coz5fd67jrj0.ap-northeast-2.rds.amazonaws.com/lemonair
    username: admin
    password: lemonair123

  server:
    ssl:
      key-store: classpath:keystore.p12
      key-store-type: PKCS12
      key-store-password: lemonair123